### ISSUE TITLE
Pinecone Uploader is broken

### ISSUE THREAD

**Issue by RunzeW2** [Unstructured-IO/unstructured-ingest#280]
Can someone please check the pinecone uploader? This while loop with total vector is wild. Killing our read units.
It will not stop querying until removing those vectors.
Under class PineconeUploader.

"""
def serverless_delete_by_record_id(self, file_data: FileData) -> None:
        logger.debug(
            f"deleting any content with metadata "
            f"{self.upload_config.record_id_key}={file_data.identifier} "
            f"from pinecone serverless index"
        )
        index = self.connection_config.get_index(pool_threads=MAX_POOL_THREADS)
        index_stats = index.describe_index_stats()
        dimension = index_stats["dimension"]
        total_vectors = index_stats["total_vector_count"]
        if total_vectors == 0:
            return
        while total_vectors > 0:
            top_k = min(total_vectors, MAX_QUERY_RESULTS)
            query_params = {
                "filter": {self.upload_config.record_id_key: {"$eq": file_data.identifier}},
                "vector": [0] * dimension,
                "top_k": top_k,
            }
            if namespace := self.upload_config.namespace:
                query_params["namespace"] = namespace
            self.delete_by_query(index=index, query_params=query_params)
            index_stats = index.describe_index_stats()
            total_vectors = index_stats["total_vector_count"]

        logger.info(
            f"deleted {total_vectors} records with metadata "
            f"{self.upload_config.record_id_key}={file_data.identifier} "
            f"from pinecone index"
        )
"""

**Comment by rbiseck3** [comment]
This PR should address this issue: https://github.com/Unstructured-IO/unstructured-ingest/pull/295
