### ISSUE TITLE
feat/pinecone_namespace

### ISSUE THREAD

**Issue by iaminov01** [Unstructured-IO/unstructured-ingest#65]
Can you please add a parameter to your pinecone writer to allow a pinecone namespace? I tested it locally and the version of the pinecone library you are using already supports this parameter so it would be a very simple fix. You basically just need to add it as a parameter to the method upsert_batch inside the class PineconeDestinationConnector in the file connector/pinecone.py (and obviously inside the Configs and whatever other methods need to be updated for this parameter to get passed down to this method). 

Just as a side note, that same upsert_batch method is using an outdated exception from the pinecone.core.client.exceptions package. The exception you are using is called ApiException however this no longer exists and was replaced by PineconeApiException.

**Comment by RunzeW2** [comment]
Hello, Can someone please address this, we saw the commit in unstrctured and it was removed, we need namespace for multi-tenancy. This should be a quick fix

**Comment by cpflow** [comment]
Would be a great and seemingly easy to implement feature

**Comment by rbiseck3** [comment]
Can you add a reference to the namespace support you're referring to in the pinecone SDK? Or the change that was originally made in the unstructured repo?

**Comment by rbiseck3** [comment]
I've opened this PR to support passing in an optional namespace: https://github.com/Unstructured-IO/unstructured-ingest/pull/159

**Comment by jaisir-shadai** [comment]
this is an important feature, please address this ASAP
