### ISSUE TITLE
Cleaning step in the Ingestion Configuration

### ISSUE THREAD

**Issue by mahmoudaymo** [Unstructured-IO/unstructured-ingest#66]
**Is your feature request related to a problem? Please describe.**
I am using the LocalRunner to ingest data locally. I am not sure in which of the configuration steps I can add some functionality to clean the text. Ideally it would be after partitioning and before chunking.

**Describe the solution you'd like**
Adding Cleaning configuration step in the Ingestion Configuration

**Describe alternatives you've considered**
Not sure where to start.

**Additional context**

**Comment by rbiseck3** [comment]
This can be done by running the pipeline twice, updating the partitioned content in the cache location, and rerunning the same pipeline. As long as the file names didn't change, it should pick up from the partitioner with the modified files. There is no built in support for custom logic between any of the current pipeline steps.
